version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1881:1880"
    networks:
      - node_net
    volumes:
      - "./data:/data"

networks:
  node_net:
