@startuml FireAlarmSystem
hide empty description
skinparam stateBackgroundColor #9fc2ff
skinparam stateBorderColor #586E75

state TemperatureControl {
  [*] ---> Idle
  Reading : value = read()

  Idle -> Reading : time_elapsed
  Reading -----> Checking

  Checking ----> Alarm : value ≥ threshold
  Checking ----> Idle  : value < threshold
  Alarm : start_alarm()

  Alarm ----> Idle : reset_alarm()
}

@enduml